version: '3.8'
networks:
  network-spotlink:
    driver: bridge

services:
  app:
    image: gchacaltanab/spotlink:latest
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - network-spotlink
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    networks:
      - network-spotlink
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    networks:
      - network-spotlink
    ports:
      - "6379:6379"

volumes:
  postgres_data: